# Generated by Django 2.2 on 2020-02-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='other_contractors_bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_info', models.CharField(max_length=500, verbose_name='Other Contractors Information')),
                ('contractor_price', models.CharField(max_length=50, verbose_name='Bid')),
            ],
            options={
                'verbose_name': 'Other Contractors',
                'verbose_name_plural': 'Other Contractors',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_number', models.CharField(max_length=500, verbose_name='Tender Number')),
                ('tender_name', models.CharField(max_length=500, verbose_name='Name of Work')),
                ('tender_submission_date', models.DateField(auto_now=True, verbose_name='Tender Submission Date')),
                ('tender_purchase_reciept', models.FileField(upload_to='', verbose_name='Tender Purchase Reciept')),
                ('tender_confirmation_reciept', models.FileField(upload_to='', verbose_name='Tender Confirmation Reciept')),
                ('physical_submission_date', models.DateField(auto_now=True, verbose_name='Physical Submission Date')),
                ('tech_bid_opening_date', models.DateField(auto_now=True, verbose_name='Technical Bid Opening Bid')),
                ('bid_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='Bid Status')),
                ('prize_bid', models.CharField(max_length=50, verbose_name='Prize Bid')),
                ('other_contractors', models.ManyToManyField(to='projects.other_contractors_bid')),
            ],
            options={
                'verbose_name': 'Tender Lists',
                'verbose_name_plural': 'Tender Lists',
            },
        ),
    ]
