# Generated by Django 2.0 on 2020-03-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_bugs_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='image',
            field=models.FileField(blank=True, upload_to='Bugs'),
        ),
    ]
