# Generated by Django 2.2 on 2020-02-13 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200213_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='physical_submission_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 16, 44, 14, 791814, tzinfo=utc), verbose_name='Physical Submission Date'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tech_bid_opening_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 16, 44, 14, 791832, tzinfo=utc), verbose_name='Technical Bid Opening Bid'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_submission_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 16, 44, 14, 791754, tzinfo=utc), verbose_name='Tender Submission Date'),
        ),
    ]
