# Generated by Django 2.0 on 2020-03-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_bugs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='bug_status',
            field=models.CharField(choices=[('Seen', 'Seen'), ('Processing', 'Processing'), ('Done', 'Done'), ['Unseen', 'Unseen']], default='Unseen', max_length=30, verbose_name='Bug Status'),
        ),
    ]
