# Generated by Django 2.0 on 2020-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_bugs_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='bug_status',
            field=models.CharField(choices=[('Unseen', 'Unseen'), ('Seen', 'Seen'), ('Processing', 'Processing'), ('Done', 'Done')], default='Unseen', max_length=30, verbose_name='Bug Status'),
        ),
    ]
