# Generated by Django 2.2 on 2020-02-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200213_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='other_contractors',
        ),
        migrations.AddField(
            model_name='tender',
            name='other_contractors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.other_contractors_bid'),
            preserve_default=False,
        ),
    ]
