# Generated by Django 2.0 on 2020-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200324_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='ticket',
            field=models.CharField(blank='True', max_length=30),
        ),
    ]
