# Generated by Django 2.2 on 2020-02-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200213_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='other_contractors',
        ),
        migrations.AddField(
            model_name='other_contractors_bid',
            name='tender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Tender'),
            preserve_default=False,
        ),
    ]
