# Generated by Django 2.0 on 2020-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_bugs_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='ticket',
            field=models.CharField(blank='False', max_length=30),
        ),
    ]
