# Generated by Django 2.2 on 2020-02-22 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200213_1642'),
        ('projects', '0006_auto_20200213_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('labours', models.ManyToManyField(to='employee.labour')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.SuperVisors')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Tender')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
            },
        ),
    ]
