# Generated by Django 2.0 on 2020-03-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200324_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
