# Generated by Django 2.2 on 2020-02-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_attendance', models.BooleanField()),
                ('add_labour', models.BooleanField()),
                ('delete_labour', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Permissions',
                'verbose_name_plural': 'Permissions',
            },
        ),
    ]
