# Generated by Django 3.0.4 on 2020-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_bugs_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='tender_description',
            field=models.TextField(default='q'),
            preserve_default=False,
        ),
    ]
