# Generated by Django 3.0.4 on 2020-04-18 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_tender_tender_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='bid_price_opening_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Bid price opening date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tender',
            name='prize_bid',
            field=models.CharField(max_length=50, verbose_name='Bid Price'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tech_bid_opening_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Technical Bid Opening Date'),
        ),
    ]
