# Generated by Django 2.2 on 2020-02-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200224_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='use_less',
            field=models.BooleanField(default=True),
        ),
    ]
