# Generated by Django 2.2 on 2020-03-17 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('image', models.FileField(blank=True, upload_to='labour_Images', verbose_name='Image')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('alter_number', models.CharField(max_length=15, verbose_name='Alternate Number')),
                ('address', models.CharField(max_length=400, verbose_name='Address')),
                ('resume', models.FileField(upload_to='Resume')),
                ('aadhar_number', models.CharField(max_length=20, verbose_name='Aadhar Number')),
                ('aadhar_photo', models.FileField(blank=True, upload_to='Aadhar_photo', verbose_name='Aadhar Card Photo')),
                ('pan_number', models.CharField(max_length=20, verbose_name='PAN Number')),
                ('pan_photo', models.FileField(blank=True, upload_to='PAN_Photo', verbose_name='PAN Card Photo')),
                ('highest_qual', models.CharField(max_length=200, verbose_name='Highest Qualifications')),
                ('highest_qual_photo', models.FileField(blank=True, upload_to='Highest_Qualification', verbose_name='Proof of Highest Qualification')),
                ('ten_certi', models.FileField(blank=True, upload_to='ten_certi', verbose_name='10th Certificate')),
                ('twelve_certi', models.FileField(blank=True, upload_to='twelve_certi', verbose_name='12th Certificate')),
                ('tech_certificate_name', models.CharField(max_length=300, verbose_name='Technical Certificate Name')),
                ('tech_certi', models.FileField(blank=True, upload_to='tech_certi', verbose_name='Technical Certificate')),
                ('UAN_number', models.CharField(max_length=200, verbose_name='UAN Number')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
            options={
                'verbose_name': 'Labour List',
                'verbose_name_plural': 'Labour List',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10, verbose_name='Shift')),
                ('is_present', models.BooleanField(default=False)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.labour')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
            options={
                'verbose_name': 'Attandance',
                'verbose_name_plural': 'Attandance',
            },
        ),
        migrations.CreateModel(
            name='SuperVisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('image', models.FileField(blank=True, upload_to='Supervisor_Images', verbose_name='Image')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('alter_number', models.CharField(max_length=15, verbose_name='Alternate Number')),
                ('address', models.CharField(max_length=400, verbose_name='Address')),
                ('resume', models.FileField(upload_to='Resume')),
                ('aadhar_number', models.CharField(max_length=20, verbose_name='Aadhar Number')),
                ('aadhar_photo', models.FileField(blank=True, upload_to='Aadhar_photo', verbose_name='Aadhar Card Photo')),
                ('pan_number', models.CharField(max_length=20, verbose_name='PAN Number')),
                ('pan_photo', models.FileField(blank=True, upload_to='PAN_Photo', verbose_name='PAN Card Photo')),
                ('highest_qual', models.CharField(max_length=200, verbose_name='Highest Qualifications')),
                ('highest_qual_photo', models.FileField(blank=True, upload_to='Highest_Qualification', verbose_name='Proof of Highest Qualification')),
                ('ten_certi', models.FileField(blank=True, upload_to='ten_certi', verbose_name='10th Certificate')),
                ('twelve_certi', models.FileField(blank=True, upload_to='twelve_certi', verbose_name='12th Certificate')),
                ('tech_certificate_name', models.CharField(max_length=300, verbose_name='Technical Certificate Name')),
                ('tech_certi', models.FileField(blank=True, upload_to='tech_certi', verbose_name='Technical Certificate')),
                ('UAN_number', models.CharField(max_length=200, verbose_name='UAN Number')),
                ('is_employee', models.BooleanField(verbose_name='Employee')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
            options={
                'verbose_name': 'Supervisors List',
                'verbose_name_plural': 'Supervisors List',
                'unique_together': {('project', 'username')},
            },
        ),
    ]
