# Generated by Django 3.0.4 on 2020-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisors',
            name='re_password',
            field=models.CharField(default='21', max_length=50),
            preserve_default=False,
        ),
    ]
