# Generated by Django 3.0.4 on 2020-04-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200418_1807'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisors',
            name='project',
            field=models.ManyToManyField(to='projects.Projects'),
        ),
        migrations.AlterUniqueTogether(
            name='supervisors',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='supervisors',
            name='project',
        ),
    ]
