# Generated by Django 2.2 on 2020-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_supervisors_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('image', models.ImageField(blank=True, upload_to='Supervisor_Images', verbose_name='Image')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('alter_number', models.CharField(max_length=15, verbose_name='Alternate Number')),
                ('address', models.CharField(max_length=400, verbose_name='Address')),
                ('resume', models.FileField(upload_to='Resume')),
                ('aadhar_number', models.CharField(max_length=20, verbose_name='Aadhar Number')),
                ('aadhar_photo', models.ImageField(blank=True, upload_to='Aadhar_photo', verbose_name='Aadhar Card Photo')),
                ('pan_number', models.CharField(max_length=20, verbose_name='PAN Number')),
                ('pan_photo', models.ImageField(blank=True, upload_to='PAN_Photo', verbose_name='PAN Card Photo')),
                ('highest_qual', models.CharField(max_length=200, verbose_name='Highest Qualifications')),
                ('highest_qual_photo', models.ImageField(blank=True, upload_to='Highest_Qualification', verbose_name='Proof of Highest Qualification')),
                ('ten_certi', models.ImageField(blank=True, upload_to='ten_certi', verbose_name='10th Certificate')),
                ('twelve_certi', models.ImageField(blank=True, upload_to='twelve_certi', verbose_name='12th Certificate')),
                ('tech_certificate_name', models.CharField(max_length=300, verbose_name='Technical Certificate Name')),
                ('tech_certi', models.ImageField(blank=True, upload_to='tech_certi', verbose_name='Technical Certificate')),
                ('UAN_number', models.CharField(max_length=200, verbose_name='UAN Number')),
            ],
            options={
                'verbose_name': 'Labour List',
                'verbose_name_plural': 'Labour List',
            },
        ),
    ]
