# Generated by Django 3.0.4 on 2020-04-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200418_1807'),
        ('employee', '0002_auto_20200424_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisors',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.Projects'),
        ),
    ]
