# Generated by Django 3.0.4 on 2020-04-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_supervisors_re_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisors',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Type password'),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='re_password',
            field=models.CharField(max_length=50, verbose_name='Retype password'),
        ),
    ]
