# Generated by Django 3.0.4 on 2020-04-24 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200424_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='supervisors',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
    ]
