# Generated by Django 2.2 on 2020-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_labour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='image',
            field=models.ImageField(blank=True, upload_to='labour_Images', verbose_name='Image'),
        ),
    ]
