# Generated by Django 2.2 on 2020-02-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200224_1017'),
        ('employee', '0004_auto_20200213_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
        migrations.AddField(
            model_name='supervisors',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
    ]
