# Generated by Django 3.0.4 on 2020-04-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200424_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('R', 'R')], default='A', max_length=10, verbose_name='Shift'),
        ),
    ]
