# Generated by Django 2.2 on 2020-02-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200224_1017'),
        ('employee', '0006_auto_20200224_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisors',
            name='username',
            field=models.CharField(default='roshan', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='supervisors',
            unique_together={('project', 'username')},
        ),
        migrations.RemoveField(
            model_name='supervisors',
            name='user',
        ),
    ]
