# Generated by Django 2.2 on 2020-02-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20200224_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisors',
            name='password',
            field=models.CharField(default='newPass', max_length=50),
            preserve_default=False,
        ),
    ]
