# Generated by Django 2.2 on 2020-02-24 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_supervisors_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10, verbose_name='Shift')),
                ('is_present', models.BooleanField(default=False)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.labour')),
            ],
            options={
                'verbose_name': 'Attandance',
                'verbose_name_plural': 'Attandance',
            },
        ),
    ]
