# Generated by Django 2.2 on 2020-03-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projects_use_less'),
        ('employee', '0009_auto_20200224_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
            preserve_default=False,
        ),
    ]
