# Generated by Django 2.2 on 2020-03-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_attendance_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='aadhar_photo',
            field=models.FileField(blank=True, upload_to='Aadhar_photo', verbose_name='Aadhar Card Photo'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='highest_qual_photo',
            field=models.FileField(blank=True, upload_to='Highest_Qualification', verbose_name='Proof of Highest Qualification'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='image',
            field=models.FileField(blank=True, upload_to='labour_Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='pan_photo',
            field=models.FileField(blank=True, upload_to='PAN_Photo', verbose_name='PAN Card Photo'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='tech_certi',
            field=models.FileField(blank=True, upload_to='tech_certi', verbose_name='Technical Certificate'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='ten_certi',
            field=models.FileField(blank=True, upload_to='ten_certi', verbose_name='10th Certificate'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='twelve_certi',
            field=models.FileField(blank=True, upload_to='twelve_certi', verbose_name='12th Certificate'),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='aadhar_photo',
            field=models.FileField(blank=True, upload_to='Aadhar_photo', verbose_name='Aadhar Card Photo'),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='highest_qual_photo',
            field=models.FileField(blank=True, upload_to='Highest_Qualification', verbose_name='Proof of Highest Qualification'),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='image',
            field=models.FileField(blank=True, upload_to='Supervisor_Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='pan_photo',
            field=models.FileField(blank=True, upload_to='PAN_Photo', verbose_name='PAN Card Photo'),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='tech_certi',
            field=models.FileField(blank=True, upload_to='tech_certi', verbose_name='Technical Certificate'),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='ten_certi',
            field=models.FileField(blank=True, upload_to='ten_certi', verbose_name='10th Certificate'),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='twelve_certi',
            field=models.FileField(blank=True, upload_to='twelve_certi', verbose_name='12th Certificate'),
        ),
    ]
